<?php

namespace AppBundle\Repository;

/**
 * ShortenUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortenUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
