<?php

namespace AppBundle\Repository;

/**
 * ShortenUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortenUrlRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get info about short url
     * @param  string $shortUrl
     * @return Entity
     */
    public function getShortUrlInfo($shortUrl)
    {
        return $this->findOneBy(
            array('short_url' => $shortUrl)
        );
    }

    /**
     * Get url records created earlier than 15 days ago
     */
    public function getOldUrls()
    {
        $criteria = new \Doctrine\Common\Collections\Criteria();
        $criteria->where($criteria->expr()->lt('create_date', (new \DateTime())->modify('-15 day') ));
        return $this->matching($criteria);
    }

}
